"""empty message

Revision ID: fe1ac8919ed6
Revises: 4c79c453196b
Create Date: 2024-08-30 14:25:17.857014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1ac8919ed6'
down_revision = '4c79c453196b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_view')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_view',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('page', sa.VARCHAR(length=100), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
